name: CI/CD to AWS EC2 with Docker Compose

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Create the .env file
    - name: Create .env file
      run: |
       echo "${{ secrets.ENV_VARS }}" > .env
       cat .env  # Debugging only, remove for production

    # Step 4: Build and Test with Docker Compose
    - name: Build and Test Docker Compose
      run: |
        docker compose -f docker-compose.yml config
        docker compose build
        docker compose up -d
        sleep 15 # Allow time for services to start
        docker ps # Verify containers are running
    - name: Tear Down Docker Containers
      run: docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures build job completes before deploying

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3
    
    # Step 2: Configure SSH Key
    - name: Configure SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > /tmp/servana-backend-key.pem
        chmod 600 /tmp/servana-backend-key.pem
    
    # Step 3: Add EC2 Host to known_hosts
    - name: Add EC2 Host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
  
    # Step 4: Ensure EC2 Permissions and Create Directory
    - name: Ensure EC2 Permissions and Create Directory
      run: |
        ssh -i /tmp/servana-backend-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        # Ensure the directory exists
        sudo mkdir -p /var/www/servanaa-backend

        # Set the appropriate permissions
        sudo chown -R ubuntu:ubuntu /var/www/servanaa-backend
        sudo chmod -R 755 /var/www/servanaa-backend
        EOF
    
    # Step 5: Copy Files to EC2
    - name: Copy Files to EC2
      run: |
        scp -i /tmp/servana-backend-key.pem -r . ubuntu@${{ secrets.EC2_HOST }}:/var/www/servanaa-backend
    
    # Step 6: Deploy Application
    - name: Deploy Application
      run: |
        ssh -i /tmp/servana-backend-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /var/www/servanaa-backend
        # docker compose down || true
        sudo docker compose up -d --build
        EOF
